language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"

cache: pip
install:
  - pip install -r requirements.txt
  - pip install pytest pytest-cov codecov

script:
  - pytest

after_success:
  - codecov
