[tool.black]
line-length = 88
target-version = ['py38', 'py39']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.pytest.ini_options]
pythonpath = [
  "src"
]

[tool.ruff]
select=["C","E","F","W","I"]
ignore=["E501","E741","C408","C901"]

[tool.ruff.isort]
lines-after-imports = 2
